server:
  port: 15002

spring:
  application:
    name: config
  cloud:
    config:
      server:
       git:
          uri: https://github.com/fengpengfei111/SpringCloud.git
          default-label: master
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/share

eureka:
  instance:
    hostname: cloud-config-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:15000/eureka

